---
kind: Secret
apiVersion: v1
metadata:
  name: parser-sqs
  namespace: {{ .NAMESPACE }}
data:
  aws-access-key-id: {{ .SQS_ACCESS_KEY_ID }}
  aws-secret-access-key: {{ .SQS_SECRET_ACCESS_KEY }}

type: Opaque
